"""Build ``.venv_kinova`` — the one interpreter that can talk to the Gen3.

    python UMArm_KINOVA/setup_env.py            # create/repair, then self-test
    python UMArm_KINOVA/setup_env.py --check    # self-test only, change nothing
    python UMArm_KINOVA/setup_env.py --force    # delete and rebuild from scratch

WHY A SEPARATE VIRTUAL ENVIRONMENT AT ALL.  ``kortex_api`` 2.6.0.post3 is not on
PyPI, its message stubs were generated by protoc 3.5, and it therefore hard-pins
``protobuf==3.5.1`` — a 2017 release that any other package wanting protobuf
would immediately break.  Installing it into the interpreter the rest of this
repo uses would put a nine-year-old protobuf under everything else.  So the
Kinova half of the lab lives in its own environment, and every Kinova entry
point is run with :data:`VENV_PYTHON` rather than with bare ``python``.

THE PROTOBUF PATCH, which is the part that is easy to lose.  protobuf 3.5.1
predates Python 3.10 and reaches for ``collections.MutableMapping``, an alias
removed in 3.10; the import dies with ``AttributeError: module 'collections' has
no attribute 'MutableMapping'`` long before any arm is contacted.  The lab's own
venv carries the same fix, applied by hand.  :func:`patch_protobuf_abc` applies
it mechanically — every ``collections.<ABC>`` becomes ``collections.abc.<ABC>``
in the two files that use them — so the environment can be thrown away and
rebuilt without anyone having to remember.  Verified here on CPython 3.13.13;
the lab also runs it on 3.11.9 and 3.12.10.

The wheel is committed at ``UMArm_KINOVA/wheels/``, so this script needs no
network access for the Kortex half.  ``numpy`` and ``scipy`` do come from PyPI.
``--no-deps`` on the wheel keeps pip from *re-resolving* protobuf, which it has
been seen to satisfy with a newer release than the pin.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

#: Where the environment lives.  Repo-root-relative and git-ignored: it holds a
#: protobuf nobody else should ever import, so it is deliberately not shared.
VENV_DIR = os.path.join(REPO, ".venv_kinova")

#: The interpreter every Kinova entry point must be run with.
VENV_PYTHON = (os.path.join(VENV_DIR, "Scripts", "python.exe") if os.name == "nt"
               else os.path.join(VENV_DIR, "bin", "python"))

#: The committed Kortex wheel.  Pure Python (``py3-none-any``), so the same file
#: works on any OS and any CPython in the supported band.
WHEEL = os.path.join(HERE, "wheels", "kortex_api-2.6.0.post3-py3-none-any.whl")

#: Pinned because kortex_api pins them, not because we chose them.
PINNED = ("protobuf==3.5.1", "deprecated==1.2.7")
#: Used by the driver's pose <-> SE(3) helpers and by the calibration solve.
MATH = ("numpy", "scipy")
#: The offline suite runs INSIDE this environment (it imports kortex_api through
#: kinova_arm), so the environment needs its own pytest.  Installed here rather
#: than left to whoever first runs the tests, because an environment that is
#: reproducible except for the way you check it is not reproducible.
TEST = ("pytest",)

#: The ABC names protobuf 3.5.1 reads off ``collections`` and Python >= 3.10
#: only exposes on ``collections.abc``.
_ABC_NAMES = ("MutableMapping", "MutableSequence", "MutableSet",
              "Mapping", "Sequence", "Set")
_ABC_RE = re.compile(r"\bcollections\.(" + "|".join(_ABC_NAMES) + r")\b")

#: protobuf 3.5.1 puts those references in exactly these two files.
_PATCH_FILES = ("internal/containers.py", "internal/well_known_types.py")


def patch_protobuf_abc(site_packages: str) -> list:
    """Rewrite ``collections.<ABC>`` to ``collections.abc.<ABC>`` in protobuf.

    Idempotent: ``collections.abc.MutableMapping`` does not match the pattern,
    so re-running changes nothing.  Returns the files it actually rewrote, which
    is empty on the second call — the caller reports that as evidence rather
    than asserting a fresh install.
    """
    changed = []
    for rel in _PATCH_FILES:
        path = os.path.join(site_packages, "google", "protobuf", *rel.split("/"))
        if not os.path.exists(path):
            raise FileNotFoundError(
                path + " is missing — protobuf 3.5.1 did not install, or a "
                "different protobuf did")
        with open(path, encoding="utf-8") as fh:
            src = fh.read()
        out = _ABC_RE.sub(lambda m: "collections.abc." + m.group(1), src)
        if out != src:
            with open(path, "w", encoding="utf-8", newline="") as fh:
                fh.write(out)
            changed.append(path)
    return changed


def _run(argv, **kw):
    print("  $", " ".join(str(a) for a in argv))
    return subprocess.run(argv, check=True, **kw)


def _site_packages(python: str) -> str:
    out = subprocess.run(
        [python, "-c", "import sysconfig;print(sysconfig.get_paths()['purelib'])"],
        check=True, capture_output=True, text=True)
    return out.stdout.strip()


def build(python=None, force: bool = False) -> str:
    """Create (or repair) the environment and return its interpreter path."""
    base = python or sys.executable
    if force and os.path.isdir(VENV_DIR):
        print("removing " + VENV_DIR)
        shutil.rmtree(VENV_DIR)
    if not os.path.exists(VENV_PYTHON):
        print("creating " + VENV_DIR + " from " + base)
        _run([base, "-m", "venv", VENV_DIR])
    if not os.path.exists(WHEEL):
        raise FileNotFoundError("the Kortex wheel is missing: " + WHEEL)

    print("installing pinned dependencies")
    _run([VENV_PYTHON, "-m", "pip", "install", "-q", "--upgrade", "pip"])
    _run([VENV_PYTHON, "-m", "pip", "install", "-q"]
         + list(PINNED) + list(MATH) + list(TEST))
    _run([VENV_PYTHON, "-m", "pip", "install", "-q", "--no-deps", WHEEL])

    changed = patch_protobuf_abc(_site_packages(VENV_PYTHON))
    print("protobuf ABC patch: %d file(s) rewritten%s"
          % (len(changed), "" if changed else " (already patched)"))
    return VENV_PYTHON


#: What :func:`check` runs inside the environment.  Everything an entry point
#: imports, plus the one Kortex message field the slow-motion moves depend on.
_PROBE = """
import sys, numpy, scipy, kortex_api
from kortex_api.autogen.client_stubs.BaseClientRpc import BaseClient
from kortex_api.autogen.client_stubs.BaseCyclicClientRpc import BaseCyclicClient
from kortex_api.autogen.messages import Base_pb2
a = Base_pb2.Action()
a.reach_pose.constraint.speed.translation = 0.05
sys.path.insert(0, REPO)
from UMArm_KINOVA.vendor import KinovaArm, pose_to_SE3
from UMArm_MOCAP.mocap_rx import MocapRx
print("python", ".".join(str(v) for v in sys.version_info[:3]),
      "| numpy", numpy.__version__, "| scipy", scipy.__version__)
print("kortex_api, KinovaArm, MocapRx, speed constraint: all OK")
"""


def check(verbose: bool = True) -> bool:
    """Import every piece inside the venv.  No network, no arm, no mocap."""
    if not os.path.exists(VENV_PYTHON):
        if verbose:
            print("MISSING: " + VENV_PYTHON
                  + "\nrun:  python UMArm_KINOVA/setup_env.py")
        return False
    probe = "REPO = " + repr(REPO) + "\n" + _PROBE
    res = subprocess.run([VENV_PYTHON, "-c", probe],
                         capture_output=True, text=True)
    if verbose:
        for line in res.stdout.splitlines():
            print(" ", line)
        # protobuf 3.5.1 greets every import with a pkg_resources deprecation
        # warning.  It is noise, not a fault, and is filtered rather than fixed
        # because fixing it means touching a pinned dependency.
        noise = ("pkg_resources", "declare_namespace")
        for line in res.stderr.splitlines():
            if not any(n in line for n in noise):
                print("  !", line)
    return res.returncode == 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="verify an existing environment, change nothing")
    ap.add_argument("--force", action="store_true",
                    help="delete and rebuild from scratch")
    ap.add_argument("--python", default=None,
                    help="base interpreter (default: the one running this)")
    args = ap.parse_args(argv)

    if args.check:
        ok = check()
        print("environment OK" if ok else "environment NOT usable")
        return 0 if ok else 2

    build(args.python, force=args.force)
    ok = check()
    print()
    print("environment OK" if ok else "environment NOT usable")
    print("run Kinova entry points with:\n  " + VENV_PYTHON)
    return 0 if ok else 2


if __name__ == "__main__":       # pragma: no cover
    raise SystemExit(main())
