r"""``SimMocap`` -- the twin's joints, pushed through the REAL receiver.

WHAT IT IS.  A :class:`UMArm_MOCAP.sim_stream.CanArmSimStream` -- already a real
:class:`~UMArm_MOCAP.canarm_mocap.CanArmMocap` fed by a producer thread instead
of by Motive -- whose joint source is the live
:class:`~digital_twin.sim_core.SimArm` rather than the analytic ``sweep_q``.
Each tick reads the arm's ``qpos`` under its lock, converts it with
``mjcf_generator.qpos_to_q``, turns it into plate poses with
``sim_stream.plate_poses_from_q``, and injects them through the receiver's own
listeners.  So the ``q`` a controller reads from :meth:`get_q` has been through
the id routing, the quaternion conversion, ``mocap_to_q``, the
publish-under-lock and the ring buffer, and ``get_state``, ``q_stale``,
``wait_fresh`` and ``latest_sample`` are the shipped implementations.  A twin
that handed a controller a ``q`` it computed itself would silently remove the
whole mocap pipeline from the thing under test.  Measured round trip, twelve
random joints in +-0.3 rad: 3.9e-16 rad worst case.

THE RULE THE RS485 ORIGINAL BROKE, AND WHY IT IS KEPT HERE.  The RS485
``SimMocap`` advanced the arm to the wall clock from its own producer thread
(its design decision D7).  **This producer never steps physics.**  On this arm
``SimMaster``'s link already advances the arm twice over -- inside every sync
edge on the cycle thread, and every 5 ms on its delivery thread -- and a third
advancer, while deterministic by invariant C5, is not free: every advance holds
``arm.lock`` across ``mj_step``, and this thread would then take that lock at
120 Hz against a cycle thread that needs it inside a 6.67 ms budget.  The budget
is already short.  Measured headless on 2026-09-10 with the fitted twin and one
board enabled, the 150 Hz cycle achieved about 124 Hz.  So the only work done
under the lock here is one copy of twelve doubles.

A SOURCE THAT HAS GONE AWAY PUBLISHES NOTHING.  *alive*, when given, is asked
before every frame; when it answers False no frame is injected, and
``get_state().stale`` turns True after ``mocap_constants.STALE_AFTER_S`` (0.25 s),
exactly as a Motive stream that stopped would.  The GUI passes
``lambda: master.link.is_open``, so disconnecting the SIM adapter reads as a
stream that died rather than as an arm frozen mid-swing.

THE KINEMATICS CHECK.  :meth:`fk_residual_m` reports, per plate, the distance
between the twin model's u-joint centre (its ``plate0..plate5`` sites, posed at
the receiver's own published ``q``) and the centre ``fkine`` predicts from that
``q`` with the measured table and ``order="yx"``.  The operator GUI prints it
on the kinematics line for the twin source.  It checks **the twin's geometry
against the kinematics**, not the kinematics against the arm: at build time it
read 0.0000 mm on all six plates, because ``mjcf_generator`` reads its chain
from the same ``CANARM_PARAMS`` table ``fkine`` does.  A non-zero reading means
the generator's chain has departed from the kinematics.

WHAT THIS DOES NOT MODEL, so a clean run is not over-read:

* **Measurement noise.**  None.  The RS485 original added 0.3 mm per plate and a
  common-mode base wobble, both measured on the RS485 rig; nobody has measured
  this arm's stream noise, and borrowing another rig's figure would be a guess
  presented as realism.  The twin's ``q`` is therefore cleaner than the metal's,
  the same direction ``sim_master``'s zero reply jitter makes the latency column
  distinguishable.
* **Markers, and Motive's 45 deg frame offset.**  The poses are generated by
  inverting the streamed-pose reader, so this is a streamed-pose receiver: it
  carries no labeled markers, **Lock plates cannot run on it**, and there is no
  45 deg azimuth error to correct.  Its ``q`` is in ``UMArm_KINEMATICS`` order,
  the same convention as the marker-registered live receiver.
* **Where the plates are.**  ``get_homos`` returns ``plate_poses_from_q``'s
  synthetic chain at ``sim_stream.DEFAULT_LINKS_M`` from the origin, not the
  twin's body poses.  ``q`` does not depend on those lengths, which is the
  invariance the reader is built on, but the rows are a plumbing fixture and
  must not be read as positions.  The twin's real centres are what
  :meth:`fk_residual_m` uses.
* **Latency.**  ``q`` is sampled at the producer's tick; Motive's own latency is
  not modelled.

RS485 ORIGINAL: ``C:\RUNZE_SRC\RS485_VEMA\UMArm_SIM\sim_mocap.py``
"""

from __future__ import annotations

import threading
import time

import numpy as np

try:  # pragma: no cover - whichever of the two import styles is live
    from . import mjcf_generator as MG
except ImportError:  # pragma: no cover
    import mjcf_generator as MG  # type: ignore[no-redef]

from UMArm_MOCAP.sim_stream import (DEFAULT_RATE_HZ, CanArmSimStream,
                                    inject_frame, plate_poses_from_q)

#: The file this module was ported from, absolute.
RS485_ORIGINAL = r"C:\RUNZE_SRC\RS485_VEMA\UMArm_SIM\sim_mocap.py"

#: The twin's joint count.  ``qpos_to_q`` is a permutation of twelve columns,
#: so a model carrying any other ``nq`` is refused at construction rather than
#: read with its columns misaligned.
N_JOINTS = 12


class SimMocap(CanArmSimStream):
    """A :class:`CanArmMocap` whose frames are the live twin's joints.

    *arm* is the :class:`~digital_twin.sim_core.SimArm` a
    :class:`~digital_twin.sim_master.SimMaster` drives (``master.arm``).
    Nothing runs until :meth:`start`, which returns ``self`` and opens nothing.
    """

    def __init__(self, arm, *, rate_hz: float = DEFAULT_RATE_HZ, alive=None,
                 site_prefix: str = "canarm_", **kwargs) -> None:
        if "q_of_t" in kwargs:
            raise TypeError("SimMocap reads q from the arm; q_of_t is not an "
                            "argument here (use CanArmSimStream for a q(t))")
        nq = int(arm.model.nq)
        if nq != N_JOINTS:
            raise ValueError(
                f"the twin model carries nq={nq}; SimMocap converts exactly "
                f"{N_JOINTS} hinges with mjcf_generator.qpos_to_q")
        super().__init__(q_of_t=self._q_now, rate_hz=rate_hz, **kwargs)
        self.arm = arm
        #: ``callable() -> bool``, or None for "always".  See the module
        #: docstring.
        self.alive = alive
        #: Ticks on which *alive* said no, so no frame was injected.  Motive's
        #: frame counter keeps running through a gap, and so does this one.
        self.frames_skipped = 0
        self._site_ids = _plate_site_ids(arm.model, site_prefix)
        self._kin_lock = threading.Lock()
        self._kin_data = None

    # ---- the producer ---------------------------------------------------
    def _q_now(self, _t: float = 0.0) -> np.ndarray:
        """The arm's joints, ``UMArm_KINEMATICS`` order.  Reads; never advances."""
        arm = self.arm
        with arm.lock:
            qpos = np.array(arm.data.qpos, dtype=float)
        return MG.qpos_to_q(qpos)

    def _produce(self) -> None:
        """``CanArmSimStream._produce`` with the *alive* gate in front of it."""
        period = 1.0 / self.rate_hz
        next_tick = time.monotonic()
        frame = 0
        while not self._sim_stop.is_set():
            alive = self.alive
            if alive is not None and not alive():
                self.frames_skipped += 1
            else:
                try:
                    poses = plate_poses_from_q(self._q_now(), self.links_m,
                                               self.rot_base, self.base_pos)
                    inject_frame(self, poses, frame_number=frame)
                except Exception as exc:
                    # Recorded where get_state() shows it, and the thread keeps
                    # going: one bad read must not kill the stream a status
                    # strip is watching.
                    self._note_error(f"twin mocap: {type(exc).__name__}: {exc}")
            frame += 1
            next_tick += period
            self._sim_stop.wait(max(0.0, next_tick - time.monotonic()))

    # ---- the kinematics check -------------------------------------------
    def fk_residual_m(self, q=None):
        """``(6,)`` metres between each twin plate site and fkine's centre, or None.

        *q* defaults to the receiver's newest published ``q``.  The sites are
        posed on a private ``MjData`` with ``mj_kinematics``, never on the
        arm's own data, so this neither takes the arm's lock nor sees a site
        position one physics step older than the joints -- after ``mj_step``
        the arm's ``site_xpos`` belongs to the pre-integration ``qpos``.
        ``None`` before the first frame, or when the model names no plate sites.
        """
        import mujoco

        from UMArm_MOCAP import canarm_frames as CF

        if self._site_ids is None:
            return None
        q = self.get_q() if q is None else np.asarray(q, dtype=float)
        if q is None:
            return None
        with self._kin_lock:
            if self._kin_data is None:
                self._kin_data = mujoco.MjData(self.arm.model)
            data = self._kin_data
            data.qpos[:] = MG.q_to_qpos(q)
            mujoco.mj_kinematics(self.arm.model, data)
            ids = list(self._site_ids)
            centres = np.array(data.site_xpos[ids], dtype=float)
            base = np.eye(4)
            base[0:3, 0:3] = np.asarray(data.site_xmat[ids[0]]).reshape(3, 3)
            base[0:3, 3] = centres[0]
        predicted = CF.fk_centres_world(q, base)
        return np.linalg.norm(predicted - centres, axis=1)


def _plate_site_ids(model, prefix: str):
    """The six plate-site ids by NAME, or None when the model lacks any of them."""
    import mujoco

    ids = []
    for name in MG.plate_site_names(prefix):
        sid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, name)
        if sid < 0:
            return None
        ids.append(int(sid))
    return tuple(ids)


__all__ = ["SimMocap", "N_JOINTS", "RS485_ORIGINAL"]
